export const options=[
    { value: "Hritik Roshan", label: "Hritik Roshan", color: "red" },
    { value: "Robert Downy Jr.", label: "Robert Downy Jr.", color: "yellow" },
    { value: "Johnny Depp", label: "Johnny Depp", color: "Johnny Depp" },
    { value: "Leonardo Dicapirio", label: "Leonardo Dicapirio", color: "blue" },
    { value: "Hritik Roshan", label: "Hritik Roshan", color: "red" },
    { value: "Robert Downy Jr.", label: "Robert Downy Jr.", color: "yellow" },
    { value: "Johnny Depp", label: "Johnny Depp", color: "Johnny Depp" },
    { value: "Leonardo Dicapirio", label: "Leonardo Dicapirio", color: "blue" },
  ]

export const indianStates=[
    {label:"Andhra Pradesh",value:"Andhra Pradesh"},
    {label:"Arunachal Pradesh",value:"Arunachal Pradesh"},
    {label:"Assam",value:"Assam"},
    {label:"Bihar",value:"Bihar"},
    {label:"Chhattisgarh",value:"Chhattisgarh"},
    {label:"Goa",value:"Goa"},
    {label:"Gujarat",value:"Gujarat"},
    {label:"Haryana",value:"Haryana"},
    {label:"Himachal Pradesh",value:"Himachal Pradesh"},
    {label:"Jammu and Kashmir",value:"Jammu and Kashmir"},
    {label:"Jharkhand",value:"Jharkhand"},
    {label:"Karnataka",value:"Karnataka"},
    {label:"Kerala",value:"Kerala"},
    {label:"Madhya Pradesh",value:"Madhya Pradesh"},
    {label:"Maharashtra",value:"Maharashtra"},
    {label:"Manipur",value:"Manipur"},
    {label:"Meghalaya",value:"Meghalaya"},
    {label:"Mizoram",value:"Mizoram"},
    {label:"Nagaland",value:"Nagaland"},
    {label:"Odisha",value:"Odisha"},
    {label:"Punjab",value:"Punjab"},
    {label:"Rajasthan",value:"Rajasthan"},
    {label:"Sikkim",value:"Sikkim"},
    {label:"Tamil Nadu",value:"Tamil Nadu"},
    {label:"Telangana",value:"Telangana"},
    {label:"Tripura",value:"Tripura"},
    {label:"Uttarakhand",value:"Uttarakhand"},
    {label:"Uttar Pradesh",value:"Uttar Pradesh"},
    {label:"West Bengal",value:"West Bengal"},
    {label:"Andaman and Nicobar Islands",value:"Andaman and Nico,bar Islands"},
    {label:"Chandigarh",value:"Chandigarh"},
    {label:"Dadra and Nagar Haveli",value:"Dadra and Nagar Haveli"},
    {label:"Daman and Diu",value:"Daman and Diu"},
    {label:"Delhi",value:"Delhi"},
    {label:"Lakshadweep",value:"Lakshadweep"},
    {label:"Puducherry",value:"Puducherry"},
]